"""rename department

Revision ID: 9444e43f2a85
Revises: cfe6bff56ef3
Create Date: 2024-03-11 20:55:47.914559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9444e43f2a85'
down_revision = 'cfe6bff56ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # op.create_table('departments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('address', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('department',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=False),
    # sa.Column('address', sa.VARCHAR(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('departments')
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
