"""rename address

Revision ID: e3979da6c737
Revises: 9444e43f2a85
Create Date: 2024-03-11 21:00:54.904892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3979da6c737'
down_revision = '9444e43f2a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
    #     batch_op.drop_column('address')
    op.alter_column('departments', 'address', new_column_name='location') 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
    #     batch_op.drop_column('location')
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
